{
    "name": "User Login Restriction and Tracking of user login | Restrict And Tracking User Login ",
    "description": """Using this module 1> user cannot login with multi device at a same time and if user login with multi device so previosly login automatically logout from system. 2> Using this module can track user login detials, 3> Using this module you can forcefully logout of all user.""",
    'summary': 'Using this module 1> user cannot login with multi device at a same time and if user login with multi device so previosly login automatically logout from system. 2> Using this module can track user login detials, 3> Using this module you can forcefully logout of all user.',
    'version': '16.5.4.3',
    'category': 'Point of Sale', 
    'sequence': 1,
    "author" : "DOTSPRIME",
    "email": 'dotsprime@gmail.com',
    "license": 'OPL-1',
    "price": 18,
    "currency": "EUR",
    'depends': ['base','base_setup'],
    'data': [ 
       'security/ir.model.access.csv',
       'views/users_views.xml',
       'views/res_config_setting_views.xml',
    ],   
    'demo': [],
    "live_test_url" : "",    
    "images": ['static/description/main_screenshot.jpg'],   
    'installable': True,
    'auto_install': False,
    'application': True,
}
