{
    'name': 'Dics Macfield',
    'version': '16.0.0.45',
    'author': 'DataInteger Consultancy Services LLP',
    'maintainer': 'DataInteger Consultancy Services LLP',
    'company': 'DataInteger Consultancy Services LLP',
    'website': 'https://www.datainteger.com',
    'category': 'report',
    'description': "",
    'depends': ['base', 'sale_management', 'account', 'stock_account', 'purchase', 'purchase_stock', 'sale', 'stock','sales_team'],
    'data': [
        'report/report.xml',
        'report/sale_order_report.xml',
        'report/purchase_order_templates.xml',
        'report/account_move_report.xml',
        'report/yellow_paper_invoice_report.xml',
        'views/product_inherit_view.xml',
        'views/res_partner_inherit_view.xml',
        'views/res_company_inherit_view.xml',
        'views/account_move_inherit_view.xml',
        'views/product_packaging_inherit_view.xml',
        'views/sale_order_inherit_view.xml',
        'views/purchase_order_inherit_view.xml',
        'views/stock_lot_view.xml',
        'views/stock_picking_type_view.xml',
        #'views/uom_uom_inherit_view.xml',
        'report/sale_order_pro_forma_report.xml',
        'report/header_footer_inherit_view.xml',
        'data/precisions_data.xml',
        'wizard/service_product_wizard_view.xml',
        'security/ir.model.access.csv',
    ],

    'installable': True,
    'application': True,
    'license': 'OPL-1',

}
# -*- coding: utf-8 -*-
